version: '3.8'

services:
  api-gateway:
    build:
      context: ./services/api-gateway
      dockerfile: Dockerfile
    ports:
      - "8000:8000"
    environment:
      - REDIS_HOST=redis
      - PDF_ANALYZER_SERVICE_URL=http://pdf-analyzer:8001
    depends_on:
      - redis
      - pdf-analyzer

  pdf-analyzer:
    build:
      context: ./services/pdf-analyzer
      dockerfile: Dockerfile
    ports:
      - "8001:8001"
    volumes:
      - pdf_temp:/tmp/pdf-analyzer

  redis:
    image: redis:latest
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data

volumes:
  redis_data:
  pdf_temp: 