apiVersion: velero.io/v1
kind: Schedule
metadata:
  name: daily-backup
  namespace: velero
spec:
  schedule: "0 1 * * *"  # Daily at 1 AM
  template:
    includedNamespaces:
    - ai-coding-bench
    - monitoring
    excludedResources:
    - nodes
    - events
    includeClusterResources: true
    storageLocation: default
    ttl: 720h  # 30 days
---
apiVersion: velero.io/v1
kind: Schedule
metadata:
  name: hourly-backup
  namespace: velero
spec:
  schedule: "0 * * * *"  # Every hour
  template:
    includedNamespaces:
    - ai-coding-bench
    excludedResources:
    - nodes
    - events
    includeClusterResources: false
    storageLocation: default
    ttl: 48h  # 2 days 